name: archethic_wallet_client
description: A client dart library to interact with Archethic Wallet RPC API.

version: 2.1.10

homepage: https://github.com/archethic-foundation/archethic-wallet-client-dart

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  # Archethic dart library for Flutter
  archethic_lib_dart: ^7.2.0
  #archethic_lib_dart:
  #  git:
  #    url: https://github.com/archethic-foundation/libdart.git
  #    ref: main
  #archethic_lib_dart:
  #  path: ../libdart-2

  # A RPC-via-deeplink communication library coded in Dart. This is dedicated to Flutter mobile applications (iOS / Android).
  deeplink_rpc: ^1.1.0

  flutter:
    sdk: flutter

  # Annotations for the freezed code-generator. This package does nothing without freezed too
  freezed_annotation: ^2.4.4

  # JSON-RPC (v2.0) utility classes. Invoke methods on another machine using JSON-formatted messages. Some assembly required.
  json_rpc_2: ^3.0.2

  # Logging lib
  logging: ^1.3.0

  # An abstraction for two-way communication channels based on the Dart Stream class.
  stream_channel: 2.1.2

  # Open deeplink urls
  url_launcher: ^6.3.1

  # Lightweight browser API bindings built around JS static interop.
  web: ^1.0.0

  # StreamChannel wrappers for WebSockets. Provides a cross-platform WebSocketChannel API, a cross-platform implementation of that API that communicates over an underlying StreamChannel.
  web_socket_channel: ^3.0.1

dev_dependencies:
  # A build system for Dart code generation and modular compilation
  build_runner: ^2.4.13

  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.5.7

  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.9.0

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.9.0

  lints: ^5.0.0

  # A full featured library for writing and running Dart tests across platforms.
  test: ^1.25.12
